import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'


export const metadata: Metadata = {
  title: 'Braeden Hall',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Fira+Code&family=M+PLUS+1+Code:wght@300;400;500;600;700&display=swap');
      </style>
      <link rel="icon" href="/cursor.svg" />
      </head>
      <body className="">{children}</body>
    </html>
  )
}
